user-service.url=http://localhost:8083

# Logging
logging.level.root=INFO
logging.level.com.mymicroservice.orderservice=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.security=INFO
logging.level.com.mymicroservice.orderservice.client.UserClient=DEBUG
logging.level.feign=DEBUG
logging.level.feign.Logger=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.org.apache.http.wire=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.com.mymicroservice.orderservice.client=DEBUG

# Liquibase
spring.liquibase.url=jdbc:postgresql://localhost:5432/orderdb
spring.liquibase.user=postgres
spring.liquibase.password=Kaiko1994Ulia

# DataBase
spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username=postgres
spring.datasource.password=Kaiko1994Ulia

# KAFKA: docker-compose -f docker-compose-kafka-only.yml up
spring.kafka.bootstrap-servers=localhost:9092

# Limited retries to fail fast in dev
spring.kafka.properties.retries=3

# Time before consumer is considered dead (faster fail in dev)
spring.kafka.consumer.properties.session.timeout.ms=10000